AGENT_RESEARCH_COORDINATOR = "Research Coordinator"
AGENT_TOPIC_RESEARCH = "Research Agent"
AGENT_RUNBOOK_PLANNING = "Runbook Planning Agent"
AGENT_RUNBOOK_SECTION_WRITING = "Section Writing Agent"
INITIAL_AGENT = AGENT_RESEARCH_COORDINATOR
AGENT_NAIVE_RAG_AGENT = "Naive RAG Agent"
