name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET: ${{ secrets.SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Pull and cache Supabase images
      - name: Pull and cache Supabase images
        uses: docker/build-push-action@v5
        with:
          pull: true
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            supabase/postgres:latest
            supabase/realtime:latest
            supabase/storage-api:latest
            supabase/gotrue:latest
            supabase/postgres-meta:latest

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        run: supabase db start

      - name: Verify generated types are checked in
        run: |
          supabase gen types typescript --local > app/lib/supabase/database.types.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet app/lib/supabase/database.types.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
