name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_db:
    runs-on: ubuntu-latest

    env:
      SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET: ${{ secrets.SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET }}
      SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID: ${{ secrets.SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID }}
      SITE_URL: ${{ vars.SITE_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('.github/workflows/ci.yml') }}

      - name: Start Supabase local development setup
        run: supabase db start

      - name: Verify generated types are checked in
        run: |
          supabase gen types typescript --local > app/lib/supabase/database.types.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet app/lib/supabase/database.types.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
      - name: Run pgTAP tests
        run: |
          supabase db reset --local
          supabase test db

  test_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Run pytest
        working-directory: ./api
        run: |
          devbox run poetry install
          devbox run poetry run pytest

  type_check_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Run type checker
        working-directory: ./api
        run: |
          devbox run poetry install
          devbox run poetry run pyright
